import { Project, Quote, LineItem, CanonicalItem, Flag, PriceBenchmark } from './types';

export interface VerifiedVendor {
  id: string;
  name: string;
  vat_number: string;
  type: string;
  city: string;
  province: string;
  region: string;
  rating: number;
  reviews_count: number;
  completed_projects: number;
  avg_scope_accuracy: number; // e.g. 99% accuracy on quotes vs actual
  categories: string[]; // category codes (01 - 20)
  has_durc: boolean;
  has_dico: boolean;
  has_insurance: boolean;
  badge_level: 'oro' | 'argento' | 'verificato';
  phone: string;
  email: string;
  description: string;
  response_time_hours: number;
}

export const MOCK_PROJECT: Project = {
  id: 'proj-01',
  user_id: 'user-dev-1',
  name: 'Ristrutturazione Appartamento Via Solferino 14',
  property_type: 'appartamento',
  surface_sqm: 85,
  location_city: 'Milano',
  location_province: 'MI',
  intervention_type: 'manutenzione_straordinaria',
  is_prima_casa: true,
  budget_target: 50000,
  notes: 'Ristrutturazione completa di quadrilocale 85 mq con rifacimento di 2 bagni, impianto elettrico e posa parquet.',
  created_at: '2026-08-01T10:00:00Z'
};

export const MOCK_VERIFIED_VENDORS: VerifiedVendor[] = [
  {
    id: 'vendor-01',
    name: 'Edilizia Moderna S.r.l.',
    vat_number: 'IT08923410962',
    type: 'Impresa Generale & Restauri',
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    rating: 4.9,
    reviews_count: 54,
    completed_projects: 86,
    avg_scope_accuracy: 99.2,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '14', '17', '18'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 02 8734 9100',
    email: 'preventivi@ediliziamoderna.it',
    description: 'Impresa generale specializzata in ristrutturazioni residenziali chiavi in mano con computi metrici dettagliati a norma di legge.',
    response_time_hours: 24
  },
  {
    id: 'vendor-02',
    name: 'Lombarda Costruzioni & Design',
    vat_number: 'IT04481920967',
    type: 'General Contractor',
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    rating: 4.8,
    reviews_count: 38,
    completed_projects: 62,
    avg_scope_accuracy: 97.5,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '11', '12', '14'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 02 4589 1230',
    email: 'info@lombardacostruzioni.com',
    description: 'Team di architetti e maestranze edili per ristrutturazioni di pregio, efficientamento energetico e finiture su misura.',
    response_time_hours: 36
  },
  {
    id: 'vendor-03',
    name: 'EdilBrianza Ristrutturazioni',
    vat_number: 'IT03391820961',
    type: 'Impresa Edile Residenziale',
    city: 'Monza',
    province: 'MB',
    region: 'Lombardia',
    rating: 4.7,
    reviews_count: 29,
    completed_projects: 47,
    avg_scope_accuracy: 96.8,
    categories: ['01', '02', '03', '04', '05', '08', '09', '14', '18'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'argento',
    phone: '+39 039 2847 112',
    email: 'contatti@edilbrianza.it',
    description: 'Oltre 20 anni di esperienza in opere murarie, rifacimento bagni e posa pavimenti su Milano e provincia di Monza.',
    response_time_hours: 48
  },
  {
    id: 'vendor-04',
    name: 'TermoIdraulica & Clima Express',
    vat_number: 'IT01928470154',
    type: 'Impiantisti Certificati',
    city: 'Milano',
    province: 'MI',
    region: 'Lombardia',
    rating: 4.9,
    reviews_count: 42,
    completed_projects: 110,
    avg_scope_accuracy: 99.5,
    categories: ['05', '07'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 02 7601 4455',
    email: 'service@termohydraulicamilano.it',
    description: 'Specialisti abilitati DiCo in impianti idrosanitari, pompe di calore e climatizzazione con corretta scissione IVA di legge.',
    response_time_hours: 12
  },
  {
    id: 'vendor-05',
    name: 'Roma Restauri & Costruzioni S.r.l.',
    vat_number: 'IT09812730584',
    type: 'Impresa Generale',
    city: 'Roma',
    province: 'RM',
    region: 'Lazio',
    rating: 4.8,
    reviews_count: 65,
    completed_projects: 94,
    avg_scope_accuracy: 98.1,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '13', '14', '17'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 06 4892 7700',
    email: 'info@romarestauri.it',
    description: 'Ristrutturazioni appartamenti e villini a Roma con preventivi trasparenti senza costi occulti.',
    response_time_hours: 24
  },
  {
    id: 'vendor-06',
    name: 'Torino Edilizia & Impianti',
    vat_number: 'IT05519280012',
    type: 'General Contractor',
    city: 'Torino',
    province: 'TO',
    region: 'Piemonte',
    rating: 4.7,
    reviews_count: 31,
    completed_projects: 53,
    avg_scope_accuracy: 97.0,
    categories: ['01', '02', '03', '04', '05', '06', '08', '09', '14'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'argento',
    phone: '+39 011 5923 100',
    email: 'preventivi@torinoedilizia.it',
    description: 'Ristrutturazioni complete e pratiche CILA/SCIA per immobili residenziali su tutta la provincia di Torino.',
    response_time_hours: 48
  },
  {
    id: 'vendor-07',
    name: 'Veneto Restauri & Design S.r.l.',
    vat_number: 'IT04491020281',
    type: 'Impresa Generale',
    city: 'Padova',
    province: 'PD',
    region: 'Veneto',
    rating: 4.9,
    reviews_count: 52,
    completed_projects: 81,
    avg_scope_accuracy: 99.1,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14', '17'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 049 8234 110',
    email: 'info@venetorestauri.it',
    description: 'Impresa certificata specializzata in ristrutturazioni residenziali chiavi in mano nelle province di Padova, Venezia e Treviso.',
    response_time_hours: 18
  },
  {
    id: 'vendor-08',
    name: 'Bologna Costruzioni & Finiture',
    vat_number: 'IT03881290372',
    type: 'General Contractor',
    city: 'Bologna',
    province: 'BO',
    region: 'Emilia-Romagna',
    rating: 4.8,
    reviews_count: 44,
    completed_projects: 68,
    avg_scope_accuracy: 98.4,
    categories: ['01', '02', '03', '04', '05', '06', '08', '09', '10', '14'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 051 6140 220',
    email: 'preventivi@bolognacostruzioni.it',
    description: 'Ristrutturazioni conformi a prezzari DEI con garanzia 24 mesi su tutti gli impianti civili.',
    response_time_hours: 24
  },
  {
    id: 'vendor-09',
    name: 'Firenze Edilizia Moderna',
    vat_number: 'IT06129480483',
    type: 'Impresa Generale',
    city: 'Firenze',
    province: 'FI',
    region: 'Toscana',
    rating: 4.7,
    reviews_count: 38,
    completed_projects: 59,
    avg_scope_accuracy: 97.8,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '14', '17'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 055 4912 800',
    email: 'contatti@firenzeedilizia.it',
    description: 'Specialisti nel restauro conservativo di appartamenti storici e moderni nel centro e provincia di Firenze.',
    response_time_hours: 24
  },
  {
    id: 'vendor-10',
    name: 'Napoli Ristrutturazioni & Impianti',
    vat_number: 'IT07991820631',
    type: 'Impresa Generale',
    city: 'Napoli',
    province: 'NA',
    region: 'Campania',
    rating: 4.8,
    reviews_count: 49,
    completed_projects: 72,
    avg_scope_accuracy: 98.0,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 081 7234 900',
    email: 'info@napoliristrutturazioni.it',
    description: 'DURC regolare, certificazioni DiCo per impianti idrotermici ed elettrici a norma di legge.',
    response_time_hours: 18
  },
  {
    id: 'vendor-11',
    name: 'Sicilia Costruzioni Generali',
    vat_number: 'IT06541890824',
    type: 'General Contractor',
    city: 'Palermo',
    province: 'PA',
    region: 'Sicilia',
    rating: 4.7,
    reviews_count: 33,
    completed_projects: 46,
    avg_scope_accuracy: 96.9,
    categories: ['01', '02', '03', '04', '05', '06', '08', '09', '14', '17'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'argento',
    phone: '+39 091 5821 300',
    email: 'preventivi@siciliacostruzioni.it',
    description: 'Ristrutturazioni complete di abitazioni e seconde case su Palermo, Catania e province siciliane.',
    response_time_hours: 36
  },
  {
    id: 'vendor-12',
    name: 'Puglia Edilizia & Soluzioni',
    vat_number: 'IT07129030721',
    type: 'Impresa Generale',
    city: 'Bari',
    province: 'BA',
    region: 'Puglia',
    rating: 4.8,
    reviews_count: 41,
    completed_projects: 64,
    avg_scope_accuracy: 98.3,
    categories: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '14'],
    has_durc: true,
    has_dico: true,
    has_insurance: true,
    badge_level: 'oro',
    phone: '+39 080 5491 200',
    email: 'info@pugliaedilizia.it',
    description: 'Impresa certificata con computi trasparenti a norma DEI per Bari, Bat e Brindisi.',
    response_time_hours: 24
  }
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'quote-a',
    project_id: 'proj-01',
    vendor_name: 'Edilizia Moderna S.r.l.',
    vendor_vat: 'IT08923410962',
    vendor_type: 'Impresa Generale',
    quote_date: '2026-08-05',
    validity_days: 30,
    storage_path: '/documents/preventivo_edilizia_moderna.pdf',
    status: 'reviewed',
    raw_total_net: 40600,
    raw_total_vat: 4600,
    raw_total_gross: 45200,
    scope_adjusted_net: 40600,
    scope_adjusted_gross: 45200,
    payment_terms: { acconto_pct: 20, sal: [30, 30], saldo_pct: 20 },
    duration_days: 75,
    penalty_clause: '€ 100 per ogni giorno di ritardo oltre la data di consegna prevista.',
    warranty_months: 24,
    extraction_confidence: 0.98,
    source: 'uploaded_pdf',
    created_at: '2026-08-05T14:20:00Z'
  },
  {
    id: 'quote-b',
    project_id: 'proj-01',
    vendor_name: 'Impresa Edile Rossi & Figli',
    vendor_vat: 'IT01293840153',
    vendor_type: 'Artigiano / Piccola Impresa',
    quote_date: '2026-08-08',
    validity_days: 15,
    storage_path: '/documents/preventivo_rossi.pdf',
    status: 'reviewed',
    raw_total_net: 36200,
    raw_total_vat: 3620,
    raw_total_gross: 39820,
    scope_adjusted_net: 47410,
    scope_adjusted_gross: 52151,
    payment_terms: { acconto_pct: 30, sal: [30, 30], saldo_pct: 10 },
    duration_days: 90,
    penalty_clause: null,
    warranty_months: 12,
    extraction_confidence: 0.92,
    source: 'uploaded_pdf',
    created_at: '2026-08-08T11:00:00Z'
  },
  {
    id: 'quote-c',
    project_id: 'proj-01',
    vendor_name: 'Costruzioni Lombarde S.A.S.',
    vendor_vat: 'IT04481920967',
    vendor_type: 'Impresa Edile',
    quote_date: '2026-08-12',
    validity_days: 45,
    storage_path: '/documents/preventivo_lombarde.pdf',
    status: 'reviewed',
    raw_total_net: 39385,
    raw_total_vat: 3938.5,
    raw_total_gross: 43323.5,
    scope_adjusted_net: 43885,
    scope_adjusted_gross: 48273.5,
    payment_terms: { acconto_pct: 40, sal: [40], saldo_pct: 20 },
    duration_days: 60,
    penalty_clause: null,
    warranty_months: 12,
    extraction_confidence: 0.94,
    source: 'uploaded_pdf',
    created_at: '2026-08-12T16:45:00Z'
  }
];

export const MOCK_LINE_ITEMS: LineItem[] = [
  // --- PREVENTIVO A (Edilizia Moderna) ---
  {
    id: 'li-a-01',
    quote_id: 'quote-a',
    raw_description: 'Allestimento cantiere, allacciamenti, protezione parti comuni condominiali e oneri sicurezza POS.',
    category_id: 'cat-01',
    category_code: '01',
    quantity: 1,
    unit: 'corpo',
    unit_price: 1250,
    total_price: 1250,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.99
  },
  {
    id: 'li-a-02',
    quote_id: 'quote-a',
    raw_description: 'Demolizione tramezzature, rimozione pavimenti, rivestimenti bagni e sanitari esistenti.',
    category_id: 'cat-02',
    category_code: '02',
    quantity: 85,
    unit: 'mq',
    unit_price: 24,
    total_price: 2040,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-a-03',
    quote_id: 'quote-a',
    raw_description: 'Calo in basso macerie, carico su autocarro e trasporto a discarica autorizzata con formulario.',
    category_id: 'cat-03',
    category_code: '03',
    quantity: 18,
    unit: 'mc',
    unit_price: 100,
    total_price: 1800,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.97
  },
  {
    id: 'li-a-04',
    quote_id: 'quote-a',
    raw_description: 'Ricostruzione tramezzi divisi in blocchi di gasbeton spessore 10 cm con rasatura e rete.',
    category_id: 'cat-04',
    category_code: '04',
    quantity: 45,
    unit: 'mq',
    unit_price: 42,
    total_price: 1890,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.96
  },
  {
    id: 'li-a-05',
    quote_id: 'quote-a',
    raw_description: 'Rifacimento completo impianto idrico-sanitario per 2 bagni e cucina con tubazioni multistrato isolato.',
    category_id: 'cat-05',
    category_code: '05',
    quantity: 14,
    unit: 'cad',
    unit_price: 280,
    total_price: 3920,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-a-06',
    quote_id: 'quote-a',
    raw_description: 'Nuovo impianto elettrico a norma CEI 64-8 compreso quadro generale, punti luce e prese bticino Living Now.',
    category_id: 'cat-06',
    category_code: '06',
    quantity: 75,
    unit: 'cad',
    unit_price: 70,
    total_price: 5250,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.99
  },
  {
    id: 'li-a-07',
    quote_id: 'quote-a',
    raw_description: 'Fornitura e posa impianto di climatizzazione monosplit inverter Daikin in pompa di calore (3 unità interne).',
    category_id: 'cat-07',
    category_code: '07',
    quantity: 1,
    unit: 'corpo',
    unit_price: 4800,
    total_price: 4800,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.95
  },
  {
    id: 'li-a-08',
    quote_id: 'quote-a',
    raw_description: 'Realizzazione massetto cementizio alleggerito ad alta resistenza per posa pavimentazione.',
    category_id: 'cat-08',
    category_code: '08',
    quantity: 85,
    unit: 'mq',
    unit_price: 40,
    total_price: 3400,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.97
  },
  {
    id: 'li-a-09',
    quote_id: 'quote-a',
    raw_description: 'Posa in opera di pavimento parquet prefinito e gres porcellanato nei bagni compreso collanti e stuccatura.',
    category_id: 'cat-09',
    category_code: '09',
    quantity: 85,
    unit: 'mq',
    unit_price: 35,
    total_price: 2975,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-a-10',
    quote_id: 'quote-a',
    raw_description: 'Fornitura parquet rovere naturale spessore 10mm e piastrelle bagni gres 60x60.',
    category_id: 'cat-10',
    category_code: '10',
    quantity: 85,
    unit: 'mq',
    unit_price: 55,
    total_price: 4675,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: false,
    confidence: 0.99
  },
  {
    id: 'li-a-14',
    quote_id: 'quote-a',
    raw_description: 'Tinteggiatura con lavabile traspirante su pareti e soffitti previa stesura di fissativo isolante.',
    category_id: 'cat-14',
    category_code: '14',
    quantity: 240,
    unit: 'mq',
    unit_price: 15,
    total_price: 3600,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-a-17',
    quote_id: 'quote-a',
    raw_description: 'Pratica edilizia CILA, direzione lavori, sicurezza cantieri e variazione catastale DOCFA.',
    category_id: 'cat-17',
    category_code: '17',
    quantity: 1,
    unit: 'corpo',
    unit_price: 4500,
    total_price: 4500,
    vat_rate: 22,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.96
  },
  {
    id: 'li-a-18',
    quote_id: 'quote-a',
    raw_description: 'Pulizia finale approfondita dell appartamento a fine cantiere.',
    category_id: 'cat-18',
    category_code: '18',
    quantity: 1,
    unit: 'corpo',
    unit_price: 500,
    total_price: 500,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: true,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.97
  },

  // --- PREVENTIVO B (Rossi & Figli) ---
  {
    id: 'li-b-02',
    quote_id: 'quote-b',
    raw_description: 'Demolizioni tramezze e sottomura.',
    category_id: 'cat-02',
    category_code: '02',
    quantity: 85,
    unit: 'mq',
    unit_price: 22,
    total_price: 1870,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.91
  },
  {
    id: 'li-b-04',
    quote_id: 'quote-b',
    raw_description: 'Nuove tavolati per divisione ambienti in mattoni forati.',
    category_id: 'cat-04',
    category_code: '04',
    quantity: 45,
    unit: 'mq',
    unit_price: 38,
    total_price: 1710,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.94
  },
  {
    id: 'li-b-05',
    quote_id: 'quote-b',
    raw_description: 'Impianto idraulico bagno principale e secondario.',
    category_id: 'cat-05',
    category_code: '05',
    quantity: 14,
    unit: 'cad',
    unit_price: 260,
    total_price: 3640,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.93
  },
  {
    id: 'li-b-06',
    quote_id: 'quote-b',
    raw_description: 'Impianto elettrico 70 punti luce con placche standard.',
    category_id: 'cat-06',
    category_code: '06',
    quantity: 70,
    unit: 'cad',
    unit_price: 65,
    total_price: 4550,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.95
  },
  {
    id: 'li-b-07',
    quote_id: 'quote-b',
    raw_description: 'Predisposizione condizionamento.',
    category_id: 'cat-07',
    category_code: '07',
    quantity: 1,
    unit: 'corpo',
    unit_price: 3200,
    total_price: 3200,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.89
  },
  {
    id: 'li-b-09',
    quote_id: 'quote-b',
    raw_description: 'Posa pavimenti e rivestimenti (misura indicativa 65 mq dichiarata dal cliente).',
    category_id: 'cat-09',
    category_code: '09',
    quantity: 65,
    unit: 'mq',
    unit_price: 30,
    total_price: 1950,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.88
  },
  {
    id: 'li-b-10',
    quote_id: 'quote-b',
    raw_description: 'Fornitura piastrelle e parquet da catalogo Rossi.',
    category_id: 'cat-10',
    category_code: '10',
    quantity: 65,
    unit: 'mq',
    unit_price: 48,
    total_price: 3120,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: false,
    confidence: 0.90
  },
  {
    id: 'li-b-14',
    quote_id: 'quote-b',
    raw_description: 'Imbiancatura classica bianca.',
    category_id: 'cat-14',
    category_code: '14',
    quantity: 240,
    unit: 'mq',
    unit_price: 12,
    total_price: 2880,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.94
  },
  {
    id: 'li-b-20',
    quote_id: 'quote-b',
    raw_description: 'Opere varie di finitura e dettagli secondo necessità [bassa confidenza].',
    category_id: 'cat-20',
    category_code: '20',
    quantity: null,
    unit: 'corpo',
    unit_price: null,
    total_price: 13280,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: null,
    includes_labor: null,
    confidence: 0.55
  },

  // --- PREVENTIVO C (Costruzioni Lombarde) ---
  {
    id: 'li-c-01',
    quote_id: 'quote-c',
    raw_description: 'Allestimento cantiere e protezioni condomino.',
    category_id: 'cat-01',
    category_code: '01',
    quantity: 1,
    unit: 'corpo',
    unit_price: 1100,
    total_price: 1100,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.97
  },
  {
    id: 'li-c-02',
    quote_id: 'quote-c',
    raw_description: 'Demolizioni complete pareti e pavimentazioni.',
    category_id: 'cat-02',
    category_code: '02',
    quantity: 85,
    unit: 'mq',
    unit_price: 45,
    total_price: 3825,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-c-03',
    quote_id: 'quote-c',
    raw_description: 'Oneri di smaltimento macerie edili.',
    category_id: 'cat-03',
    category_code: '03',
    quantity: 18,
    unit: 'mc',
    unit_price: 95,
    total_price: 1710,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.96
  },
  {
    id: 'li-c-04',
    quote_id: 'quote-c',
    raw_description: 'Costruzione tavolati divisori.',
    category_id: 'cat-04',
    category_code: '04',
    quantity: 45,
    unit: 'mq',
    unit_price: 40,
    total_price: 1800,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.95
  },
  {
    id: 'li-c-05',
    quote_id: 'quote-c',
    raw_description: 'Impianto idrosanitario per 2 bagni e 1 cucina.',
    category_id: 'cat-05',
    category_code: '05',
    quantity: 14,
    unit: 'cad',
    unit_price: 275,
    total_price: 3850,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.97
  },
  {
    id: 'li-c-06',
    quote_id: 'quote-c',
    raw_description: 'Impianto elettrico completo certificato 80 punti.',
    category_id: 'cat-06',
    category_code: '06',
    quantity: 80,
    unit: 'cad',
    unit_price: 68,
    total_price: 5440,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.98
  },
  {
    id: 'li-c-07',
    quote_id: 'quote-c',
    raw_description: 'Fornitura e installazione Caldaia a condensazione e Pompa di calore dual split (Bene Significativo).',
    category_id: 'cat-07',
    category_code: '07',
    quantity: 1,
    unit: 'corpo',
    unit_price: 7500,
    total_price: 7500,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.96
  },
  {
    id: 'li-c-08',
    quote_id: 'quote-c',
    raw_description: 'Sottofondo e massetto per pavimenti.',
    category_id: 'cat-08',
    category_code: '08',
    quantity: 85,
    unit: 'mq',
    unit_price: 36,
    total_price: 3060,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.95
  },
  {
    id: 'li-c-09',
    quote_id: 'quote-c',
    raw_description: 'Posa pavimenti e rivestimenti.',
    category_id: 'cat-09',
    category_code: '09',
    quantity: 85,
    unit: 'mq',
    unit_price: 32,
    total_price: 2720,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: false,
    includes_labor: true,
    confidence: 0.97
  },
  {
    id: 'li-c-10',
    quote_id: 'quote-c',
    raw_description: 'Fornitura parquet e gres.',
    category_id: 'cat-10',
    category_code: '10',
    quantity: 85,
    unit: 'mq',
    unit_price: 52,
    total_price: 4420,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: false,
    confidence: 0.98
  },
  {
    id: 'li-c-14',
    quote_id: 'quote-c',
    raw_description: 'Rasatura e tinteggiatura.',
    category_id: 'cat-14',
    category_code: '14',
    quantity: 240,
    unit: 'mq',
    unit_price: 14,
    total_price: 3360,
    vat_rate: 10,
    pricing_mode: 'a_misura',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.96
  },
  {
    id: 'li-c-18',
    quote_id: 'quote-c',
    raw_description: 'Pulizia finale cantiere.',
    category_id: 'cat-18',
    category_code: '18',
    quantity: 1,
    unit: 'corpo',
    unit_price: 600,
    total_price: 600,
    vat_rate: 10,
    pricing_mode: 'a_corpo',
    is_optional: false,
    includes_materials: true,
    includes_labor: true,
    confidence: 0.95
  }
];

function lineById(id: string): LineItem {
  const item = MOCK_LINE_ITEMS.find((line) => line.id === id);
  if (!item) {
    throw new Error(`Voce di computo mancante: ${id}`);
  }
  return item;
}

export const MOCK_CANONICAL_ITEMS: CanonicalItem[] = [
  {
    id: 'canon-01',
    project_id: 'proj-01',
    category_id: 'cat-01',
    category_code: '01',
    canonical_description: 'Allestimento cantiere, recinzione, protezione parti comuni e oneri di sicurezza POS',
    consensus_quantity: 1,
    consensus_unit: 'corpo',
    present_in_quote_ids: ['quote-a', 'quote-c'],
    missing_from_quote_ids: ['quote-b'],
    line_item_map: {
      'quote-a': lineById('li-a-01'),
      'quote-c': lineById('li-c-01')
    },
    estimated_missing_price: 1175
  },
  {
    id: 'canon-02',
    project_id: 'proj-01',
    category_id: 'cat-02',
    category_code: '02',
    canonical_description: 'Demolizione tramezze, rimozione pavimentazione e rivestimenti esistenti',
    consensus_quantity: 85,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-02'),
      'quote-b': lineById('li-b-02'),
      'quote-c': lineById('li-c-02')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-03',
    project_id: 'proj-01',
    category_id: 'cat-03',
    category_code: '03',
    canonical_description: 'Cariaggio, carico e trasporto maceri a discarica autorizzata con formulari',
    consensus_quantity: 18,
    consensus_unit: 'mc',
    present_in_quote_ids: ['quote-a', 'quote-c'],
    missing_from_quote_ids: ['quote-b'],
    line_item_map: {
      'quote-a': lineById('li-a-03'),
      'quote-c': lineById('li-c-03')
    },
    estimated_missing_price: 1755
  },
  {
    id: 'canon-04',
    project_id: 'proj-01',
    category_id: 'cat-04',
    category_code: '04',
    canonical_description: 'Opere murarie per costruzione nuovi tramezzi divisori intonacati',
    consensus_quantity: 45,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-04'),
      'quote-b': lineById('li-b-04'),
      'quote-c': lineById('li-c-04')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-05',
    project_id: 'proj-01',
    category_id: 'cat-05',
    category_code: '05',
    canonical_description: 'Impianto idrico-sanitario completo per 2 bagni e 1 cucina',
    consensus_quantity: 14,
    consensus_unit: 'cad',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-05'),
      'quote-b': lineById('li-b-05'),
      'quote-c': lineById('li-c-05')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-06',
    project_id: 'proj-01',
    category_id: 'cat-06',
    category_code: '06',
    canonical_description: 'Impianto elettrico sotto traccia a norma CEI 64-8 con quadro generale e prese',
    consensus_quantity: 75,
    consensus_unit: 'cad',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-06'),
      'quote-b': lineById('li-b-06'),
      'quote-c': lineById('li-c-06')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-07',
    project_id: 'proj-01',
    category_id: 'cat-07',
    category_code: '07',
    canonical_description: 'Impianto di climatizzazione e termico in pompa di calore (multi-split)',
    consensus_quantity: 1,
    consensus_unit: 'corpo',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-07'),
      'quote-b': lineById('li-b-07'),
      'quote-c': lineById('li-c-07')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-08',
    project_id: 'proj-01',
    category_id: 'cat-08',
    category_code: '08',
    canonical_description: 'Realizzazione massetto cementizio sottofondo per posa pavimentazione',
    consensus_quantity: 85,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-c'],
    missing_from_quote_ids: ['quote-b'],
    line_item_map: {
      'quote-a': lineById('li-a-08'),
      'quote-c': lineById('li-c-08')
    },
    estimated_missing_price: 3230
  },
  {
    id: 'canon-09',
    project_id: 'proj-01',
    category_id: 'cat-09',
    category_code: '09',
    canonical_description: 'Posa in opera di parquet prefinito e rivestimenti bagni con stuccatura',
    consensus_quantity: 85,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-09'),
      'quote-b': lineById('li-b-09'),
      'quote-c': lineById('li-c-09')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-10',
    project_id: 'proj-01',
    category_id: 'cat-10',
    category_code: '10',
    canonical_description: 'Fornitura materiali pavimento parquet rovere e piastrelle gres',
    consensus_quantity: 85,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-10'),
      'quote-b': lineById('li-b-10'),
      'quote-c': lineById('li-c-10')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-14',
    project_id: 'proj-01',
    category_id: 'cat-14',
    category_code: '14',
    canonical_description: 'Rasatura, preparazione pareti e tinteggiatura lavabile traspirante',
    consensus_quantity: 240,
    consensus_unit: 'mq',
    present_in_quote_ids: ['quote-a', 'quote-b', 'quote-c'],
    missing_from_quote_ids: [],
    line_item_map: {
      'quote-a': lineById('li-a-14'),
      'quote-b': lineById('li-b-14'),
      'quote-c': lineById('li-c-14')
    },
    estimated_missing_price: 0
  },
  {
    id: 'canon-17',
    project_id: 'proj-01',
    category_id: 'cat-17',
    category_code: '17',
    canonical_description: 'Pratica edilizia CILA, Direzione Lavori, Sicurezza e Accatastamento DOCFA',
    consensus_quantity: 1,
    consensus_unit: 'corpo',
    present_in_quote_ids: ['quote-a'],
    missing_from_quote_ids: ['quote-b', 'quote-c'],
    line_item_map: {
      'quote-a': lineById('li-a-17')
    },
    estimated_missing_price: 4500
  },
  {
    id: 'canon-18',
    project_id: 'proj-01',
    category_id: 'cat-18',
    category_code: '18',
    canonical_description: 'Pulizia finale di cantiere e sanificazione post-lavori',
    consensus_quantity: 1,
    consensus_unit: 'corpo',
    present_in_quote_ids: ['quote-a', 'quote-c'],
    missing_from_quote_ids: ['quote-b'],
    line_item_map: {
      'quote-a': lineById('li-a-18'),
      'quote-c': lineById('li-c-18')
    },
    estimated_missing_price: 550
  }
];

export const MOCK_FLAGS: Flag[] = [
  {
    id: 'flag-b-01',
    quote_id: 'quote-b',
    severity: 'critical',
    rule_code: 'MISSING_WORK',
    message: 'Lavorazione fondamentale omessa: Smaltimento macerie e trasporti in discarica (Cat. 03).',
    evidence: 'Presenti 85 mq di demolizioni nel preventivo ma nessuna voce di carico o smaltimento in discarica autorizzata.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-b-02',
    quote_id: 'quote-b',
    severity: 'critical',
    rule_code: 'NO_SAFETY_COSTS',
    message: 'Nessun onere di sicurezza o allestimento cantiere specificato (Cat. 01).',
    evidence: 'Manca la voce obbligatoria per legge su recinzioni, dispositivi di sicurezza e POS.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-b-03',
    quote_id: 'quote-b',
    severity: 'critical',
    rule_code: 'MISSING_WORK',
    message: 'Realizzazione massetto di sottofondo omessa (Cat. 08).',
    evidence: 'Preventivata la posa di pavimenti ma senza preparazione del sottofondo. Rischio di contesa in corso d’opera.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-b-04',
    quote_id: 'quote-b',
    severity: 'warning',
    rule_code: 'QUANTITY_MISMATCH',
    message: 'Discrepanza di quantità sulle pavimentazioni: quotati 65 mq invece dei 85 mq misurati sugli altri preventivi (-23.5%).',
    evidence: 'Riga 6: Posa pavimenti indicata per 65 mq (superficie appartamento 85 mq). Prezzo finale sottostimato di circa € 3.300.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-b-05',
    quote_id: 'quote-b',
    severity: 'warning',
    rule_code: 'VAGUE_ITEM',
    message: 'Voce vaga ad alta incertezza (Cat. 20 - Voci non classificabili).',
    evidence: 'Riga 9: "Opere varie di finitura" quotata € 13.280 a corpo senza dettaglio delle lavorazioni comprese.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-b-06',
    quote_id: 'quote-b',
    severity: 'info',
    rule_code: 'PROFESSIONAL_FEES_MISSING',
    message: 'Nessuna voce per CILA, Direzione Lavori o accatastamento (Cat. 17).',
    evidence: 'Verificare se le pratiche edilizie sono a carico del committente o affidate a un tecnico esterno.',
    created_at: '2026-08-08T11:05:00Z'
  },
  {
    id: 'flag-c-01',
    quote_id: 'quote-c',
    severity: 'critical',
    rule_code: 'ADVANCE_TOO_HIGH',
    message: 'Acconto iniziale richiesto superiore al limite consigliato: 40% del totale (Max consigliato 30%).',
    evidence: 'Termini di pagamento: Acconto 40% alla firma (€ 15.754 netti), SAL 40%, Saldo 20%.',
    created_at: '2026-08-12T16:48:00Z'
  },
  {
    id: 'flag-c-02',
    quote_id: 'quote-c',
    severity: 'warning',
    rule_code: 'SIGNIFICANT_GOODS_VAT',
    message: 'Anomalia fiscale IVA: Impianto termico/climatizzazione (Bene Significativo € 7.500) quotato interamente al 10% IVA.',
    evidence: 'I beni significativi usufruiscono dell’IVA agevolata al 10% solo fino a concorrenza del valore della manodopera. L’eccedenza va fatturata al 22%. Rischio sanzione fiscale o conguaglio.',
    created_at: '2026-08-12T16:48:00Z'
  },
  {
    id: 'flag-c-03',
    quote_id: 'quote-c',
    severity: 'warning',
    rule_code: 'UNIT_PRICE_OUTLIER',
    message: 'Prezzo unitario fuori mercato (Outlier): Demolizioni a € 45/mq (Benchmark Milano p75: € 28/mq).',
    evidence: 'Riga 2: Demolizioni quotate € 45/mq (+60.7% rispetto al 75° percentile di provincia).',
    created_at: '2026-08-12T16:48:00Z'
  },
  {
    id: 'flag-c-04',
    quote_id: 'quote-c',
    severity: 'warning',
    rule_code: 'NO_PENALTY',
    message: 'Assenza di clausola penale per ritardo nella consegna dei lavori.',
    evidence: 'Nel contratto non è specificata alcuna penale giornaliera in caso di sforamento dei 60 giorni pattuiti.',
    created_at: '2026-08-12T16:48:00Z'
  }
];

export const MOCK_PRICE_BENCHMARKS: PriceBenchmark[] = [
  { id: 'bm-01', category_id: 'cat-01', province: 'MI', unit: 'corpo', p25: 800, p50: 1150, p75: 1500, sample_size: 42, updated_at: '2026-08-01' },
  { id: 'bm-02', category_id: 'cat-02', province: 'MI', unit: 'mq', p25: 18, p50: 22, p75: 28, sample_size: 128, updated_at: '2026-08-01' },
  { id: 'bm-03', category_id: 'cat-03', province: 'MI', unit: 'mc', p25: 75, p50: 95, p75: 120, sample_size: 94, updated_at: '2026-08-01' },
  { id: 'bm-04', category_id: 'cat-04', province: 'MI', unit: 'mq', p25: 32, p50: 40, p75: 48, sample_size: 86, updated_at: '2026-08-01' },
  { id: 'bm-05', category_id: 'cat-05', province: 'MI', unit: 'cad', p25: 220, p50: 275, p75: 320, sample_size: 150, updated_at: '2026-08-01' },
  { id: 'bm-06', category_id: 'cat-06', province: 'MI', unit: 'cad', p25: 55, p50: 68, p75: 82, sample_size: 210, updated_at: '2026-08-01' },
  { id: 'bm-08', category_id: 'cat-08', province: 'MI', unit: 'mq', p25: 30, p50: 38, p75: 45, sample_size: 112, updated_at: '2026-08-01' },
  { id: 'bm-09', category_id: 'cat-09', province: 'MI', unit: 'mq', p25: 28, p50: 34, p75: 42, sample_size: 180, updated_at: '2026-08-01' }
];

